default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: climate_hackathon_development
  username: climate_hackathon
  password: '1234'


test:
  <<: *default
  host: localhost
  database: climate_hackathon_test
  username: climate_hackathon
  password: '1234'

production:
  <<: *default
  host: localhost
  database: climate_hackathon_production
  username: climate_hackathon
  password: '1234'
