default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: climate_hackathon_development

test:
  <<: *default
  database: climate_hackathon_test

production:
  <<: *default
  database: climate_hackathon_production
  username: climate_hackathon
  password: <%= ENV['CLIMATE_HACKATHON_DATABASE_PASSWORD'] %>
